const products = [
  {
    title: 'cirkelsåg',
    borrowed: false,
    image: '../assets/product-pictures/cirkelsag.jpg',
    category: 'snickeri',
    reservedFrom: null,
    reservedTo: null,
  },
  {
    title: 'fixkam',
    borrowed: true,
    image: '../assets/product-pictures/fixkam.jpg',
    category: 'plattsattning',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'gummihammare',
    borrowed: true,
    image: '../assets/product-pictures/gummihammare.jpg',
    category: 'multi',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'kakel-, klinkersskär',
    borrowed: true,
    image: '../assets/product-pictures/kakelskar.jpg',
    category: 'plattsattning',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'korslaser',
    borrowed: true,
    image: '../assets/product-pictures/korslaser.jpg',
    category: 'multi',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'murslev',
    borrowed: true,
    image: '../assets/product-pictures/murslev.jpg',
    category: 'mureri',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'putsbräda-Svamp',
    borrowed: true,
    image: '../assets/product-pictures/putsbrada-svamp.jpg',
    category: 'plattsattning',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'putsbräda-Gummisvamp',
    borrowed: true,
    image: '../assets/product-pictures/putsbrada-gummisvamp.jpg',
    category: 'mureri',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'spackelspade',
    borrowed: true,
    image: '../assets/product-pictures/spackel-liten.jpg',
    category: 'maleri',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'bredspackel',
    borrowed: true,
    image: '../assets/product-pictures/spackel-stor.jpg',
    category: 'maleri',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'tigersåg',
    borrowed: true,
    image: '../assets/product-pictures/tigersag.jpg',
    category: 'snickeri',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'vattenpass-40 cm',
    borrowed: true,
    image: '../assets/product-pictures/vattenpass-40cm',
    category: 'multi',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'vattenpass-80 cm',
    borrowed: true,
    image: '../assets/product-pictures/vattenpass-80cm',
    category: 'multi',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },
  {
    title: 'vattenpass-200 cm',
    borrowed: true,
    image: '../assets/product-pictures/vattenpass-200cm.jpg',
    category: 'multi',
    reservedFrom: '2000-04-15',
    reservedTo: '2000-05-11',
  },

]

export { products };